# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Do Or Dev
paginate:       10
baseurl:        ""
url:            "https://smendoza.me/blog"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Sergio Mendoza
  url:          https://smendoza.me
  email:        smendoza787@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/smendoza787/blog

# Gems
gems:
  - jekyll-paginate
